extends:
  - '@openreachtech'
rules:
  function-paren-newline:
    - off # error # 👀
    - consistent # multiline
  jsdoc/imports-as-dependencies:
    - off # error # 👀
  jsdoc/informative-docs:
    - off # error # 👀
    - aliases:
        - an
        - our
      uselessWords:
        - a
        - an
        - i
        - in
        - of
        - s
        - the
